package de.fhdw.set.bfwd425abfax425a.prg2.exercises.exercise090;

public enum ChemicalSymbol {
    H("Wasserstoff", 1),
    HE("Helium", 2),
    LI("Lithium", 3),
    BE("Beryllium", 4),
    B("Bor", 5),
    C("Kohlenstoff", 6),
    N("Stickstoff", 7),
    O("Sauerstoff", 8),
    F("Fluor", 9),
    NE("Neon", 10),
    NA("Natrium", 11),
    MG("Magnesium", 12),
    AL("Aluminium", 13),
    SI("Silicium", 14),
    P("Phosphor", 15),
    S("Schwefel", 16),
    CL("Chlor", 17),
    AR("Argon", 18),
    K("Kalium", 19),
    CA("Calcium", 20),
    SC("Scandium", 21),
    TI("Titan", 22),
    V("Vanadium", 23),
    CR("Chrom", 24),
    MN("Mangan", 25),
    FE("Eisen", 26),
    CO("Cobalt", 27),
    NI("Nickel", 28),
    CU("Kupfer", 29),
    ZN("Zink", 30),
    GA("Gallium", 31),
    GE("Germanium", 32),
    AS("Arsen", 33),
    SE("Selen", 34),
    BR("Brom", 35),
    KR("Krypton", 36),
    RB("Rubidium", 37),
    SR("Strontium", 38),
    Y("Yttrium", 39),
    ZR("Zirconium", 40),
    NB("Niob", 41),
    MO("Molybdän", 42),
    TC("Technetium", 43),
    RU("Ruthenium", 44),
    RH("Rhodium", 45),
    PD("Palladium", 46),
    AG("Silber", 47),
    CD("Cadmium", 48),
    IN("Indium", 49),
    SN("Zinn", 50),
    SB("Antimon", 51),
    TE("Tellur", 52),
    I("Iod", 53),
    XE("Xenon", 54),
    CS("Caesium", 55),
    BA("Barium", 56),
    LA("Lanthan", 57),
    CE("Cer", 58),
    PR("Praseodym", 59),
    ND("Neodym", 60),
    PM("Promethium", 61),
    SM("Samarium", 62),
    EU("Europium", 63),
    GD("Gadolinium", 64),
    TB("Terbium", 65),
    DY("Dysprosium", 66),
    HO("Holmium", 67),
    ER("Erbium", 68),
    TM("Thulium", 69),
    YB("Ytterbium", 70),
    LU("Lutetium", 71),
    HF("Hafnium", 72),
    TA("Tantal", 73),
    W("Wolfram", 74),
    RE("Rhenium", 75),
    OS("Osmium", 76),
    IR("Iridium", 77),
    PT("Platin", 78),
    AU("Gold", 79),
    HG("Quecksilber", 80),
    TL("Thallium", 81),
    PB("Blei", 82),
    BI("Wismut", 83),
    PO("Polonium", 84),
    AT("Astat", 85),
    RN("Radon", 86),
    FR("Francium", 87),
    RA("Radium", 88),
    AC("Actinium", 89),
    TH("Thorium", 90),
    PA("Protactinium", 91),
    U("Uran", 92),
    NP("Neptunium", 93),
    PU("Plutonium", 94),
    AM("Americium", 95),
    CM("Curium", 96),
    BK("Berkelium", 97),
    CF("Californium", 98),
    ES("Einsteinium", 99),
    FM("Fermium", 100),
    MD("Mendelevium", 101),
    NO("Nobelium", 102),
    LR("Lawrencium", 103),
    RF("Rutherfordium", 104),
    DB("Dubnium", 105),
    SG("Seaborgium", 106),
    BH("Bohrium", 107),
    HS("Hassium", 108),
    MT("Meitnerium", 109),
    DS("Darmstadtium", 110),
    RG("Roentgenium", 111),
    CN("Copernicium", 112),
    NH("Nihonium", 113),
    FL("Flerovium", 114),
    MC("Moscovium", 115),
    LV("Livermorium", 116),
    TS("Tenness", 117),
    OG("Oganesson", 118);

    private String mName;
    private int mOrd;

    ChemicalSymbol(String name, int ord) {
        mName = name;
        mOrd = ord;
    }

    public String getName() {
        return mName;
    }

    public int getOrd() {
        return mOrd;
    }

}
